//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppDataAccess.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public int IdNumber { get; set; }
        public string Name { get; set; }
        public string Surename { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public byte Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string ContactNumber { get; set; }
        public int Contract { get; set; }
    
        public virtual Contract Contract1 { get; set; }
    }
}
